### ISSUE TITLE
Issue 3: Testing loadDatabase.js and webServer.js

### ISSUE THREAD

**Issue by VAISHNAVREDDYDANDU** [Ankith080/Project5#21]
The issue at hand pertains to the testing of two key components within a software system - loadDatabase.js and webServer.js. These components play integral roles in the overall functionality of the application. The purpose of this testing effort is to ensure the reliability, correctness, and performance of these components in the given software system

**Comment by Ankith080** [comment]
Great job on completing the testing for loadDatabase.js and webserver.js. It would be beneficial to also conduct performance testing to ensure these components handle scaling well as the project grows.
