### ISSUE TITLE
Updating loginRegister.jsx and loginRegister.css

### ISSUE THREAD

**Issue by Ankith080** [Ankith080/Project5#34]
Add password field and enhance login for added security.

**Comment by NavyaSree1603** [comment]
This issue has been addressed! I’ve added the password field and enhanced the login functionality for better security in loginRegister.jsx and loginRegister.css. Everything has been tested and is now live. Thank you for your input, @Ankith080! If you have any further suggestions or feedback, feel free to reach out. Closing this issue now!
